import type { Merchant, GiftProduct, CategoryType, MerchantRoleType } from "../shared/schema";

export const merchants: Merchant[] = [
  {
    id: "merchant-1",
    name: "Cafe Em Nazih",
    description: "A beloved Beirut institution serving the finest Lebanese coffee and pastries since 1960. Known for their traditional Arabic coffee and house-made maamoul.",
    city: "Beirut",
    area: "Hamra",
    address: "Hamra Street, Beirut, Lebanon",
    phone: "+961 1 345 678",
    hours: "7:00 AM - 11:00 PM",
    logoUrl: "https://images.unsplash.com/photo-1559305616-3f99cd43e353?w=200&h=200&fit=crop",
    coverUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=400&fit=crop",
    isActive: true,
    rating: 4.8,
    reviewCount: 324,
    creditMinAmount: 250000,
    creditMaxAmount: 5000000,
    creditPresetAmounts: [500000, 1000000, 2000000],
    creditIsEnabled: true,
  },
  {
    id: "merchant-2",
    name: "Bachir Ice Cream",
    description: "Lebanon's most famous ice cream parlor, crafting artisanal ashta and mastic ice cream with recipes passed down through generations.",
    city: "Beirut",
    area: "Sassine",
    address: "Sassine Square, Ashrafieh, Beirut",
    phone: "+961 1 234 567",
    hours: "10:00 AM - 12:00 AM",
    logoUrl: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=200&h=200&fit=crop",
    coverUrl: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=800&h=400&fit=crop",
    isActive: true,
    rating: 4.9,
    reviewCount: 567,
    creditMinAmount: 0,
    creditMaxAmount: 0,
    creditPresetAmounts: [],
    creditIsEnabled: false,
  },
  {
    id: "merchant-3",
    name: "Tawlet Byblos",
    description: "Farm-to-table Lebanese cuisine celebrating the country's rich culinary heritage. Each dish tells a story of Lebanon's diverse regions.",
    city: "Byblos",
    area: "Old Souk",
    address: "Old Souk, Byblos, Lebanon",
    phone: "+961 9 876 543",
    hours: "12:00 PM - 10:00 PM",
    logoUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=200&h=200&fit=crop",
    coverUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=400&fit=crop",
    isActive: true,
    rating: 4.7,
    reviewCount: 198,
    creditMinAmount: 300000,
    creditMaxAmount: 4000000,
    creditPresetAmounts: [500000, 1000000, 1500000],
    creditIsEnabled: true,
  },
];

export type MerchantUserSeed = {
  id: string;
  merchantId: string;
  role: MerchantRoleType;
  email: string;
  password: string;
  isActive: boolean;
};

export const merchantUsers: MerchantUserSeed[] = [
  {
    id: "merchant-user-1",
    merchantId: "merchant-1",
    role: "owner",
    email: "owner@cafenazih.com",
    password: "localtreats",
    isActive: true,
  },
  {
    id: "merchant-user-2",
    merchantId: "merchant-1",
    role: "staff",
    email: "staff@cafenazih.com",
    password: "localtreats",
    isActive: true,
  },
  {
    id: "merchant-user-3",
    merchantId: "merchant-3",
    role: "owner",
    email: "owner@tawletbyblos.com",
    password: "localtreats",
    isActive: true,
  },
];

export const giftProducts: GiftProduct[] = [
  {
    id: "prod-1",
    merchantId: "merchant-1",
    title: "2 Cappuccinos",
    description: "Two perfectly crafted cappuccinos with house-roasted beans",
    price: 8,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=400&fit=crop",
    category: "coffee" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any hot drink up to $4 each",
  },
  {
    id: "prod-2",
    merchantId: "merchant-1",
    title: "Arabic Coffee Set",
    description: "Traditional Arabic coffee with cardamom and a plate of maamoul cookies",
    price: 12,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1578899544667-5e5e3a576024?w=400&h=400&fit=crop",
    category: "coffee" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any coffee + pastry combo up to $12",
  },
  {
    id: "prod-3",
    merchantId: "merchant-1",
    title: "Breakfast Combo",
    description: "Full Lebanese breakfast: labneh, zaatar manoushe, olives, fresh juice",
    price: 15,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any breakfast item up to $15",
  },
  {
    id: "prod-4",
    merchantId: "merchant-1",
    title: "Pastry Box (6 pcs)",
    description: "Assorted Lebanese pastries: baklava, maamoul, namoura, and more",
    price: 18,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any 6 pastries from the display",
  },
  {
    id: "prod-5",
    merchantId: "merchant-1",
    title: "Coffee Lovers Bundle",
    description: "4 specialty drinks + a bag of house-blend beans to take home",
    price: 25,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=400&fit=crop",
    category: "coffee" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any 4 drinks + 250g beans",
  },
  {
    id: "prod-6",
    merchantId: "merchant-1",
    title: "Afternoon Tea for Two",
    description: "A selection of teas, finger sandwiches, and petit fours",
    price: 22,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop",
    category: "coffee" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any tea set for two up to $22",
  },
  {
    id: "prod-7",
    merchantId: "merchant-1",
    title: "Weekend Brunch",
    description: "Eggs benedict Lebanese style with halloumi, labneh spread, fresh juice",
    price: 20,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any brunch item up to $20",
  },
  {
    id: "prod-8",
    merchantId: "merchant-1",
    title: "Knefeh Platter",
    description: "Warm, golden knefeh drizzled with sugar syrup, served with kaak",
    price: 10,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1579697096985-41fe1430e5df?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any dessert up to $10",
  },
  {
    id: "prod-9",
    merchantId: "merchant-2",
    title: "Ashta Ice Cream Cup",
    description: "Signature ashta (cream) ice cream with pistachios and rose water",
    price: 6,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any single scoop flavor",
  },
  {
    id: "prod-10",
    merchantId: "merchant-2",
    title: "Ice Cream Duo",
    description: "Two scoops of your choice: mastic, ashta, chocolate, or seasonal flavor",
    price: 10,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any two scoops",
  },
  {
    id: "prod-11",
    merchantId: "merchant-2",
    title: "Family Sundae",
    description: "A spectacular sundae for 4 with mixed flavors, toppings, and wafers",
    price: 22,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any family-size creation up to $22",
  },
  {
    id: "prod-12",
    merchantId: "merchant-2",
    title: "Ice Cream Cake",
    description: "Custom ice cream cake with layers of ashta and pistachio, serves 6-8",
    price: 35,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any cake from the selection",
  },
  {
    id: "prod-13",
    merchantId: "merchant-2",
    title: "Mastic Milkshake",
    description: "Thick and creamy mastic milkshake topped with crushed pistachios",
    price: 8,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any milkshake flavor",
  },
  {
    id: "prod-14",
    merchantId: "merchant-2",
    title: "Dessert Platter",
    description: "A grand platter: ice cream, baklava bites, fruit, and chocolate sauce",
    price: 28,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any dessert combo up to $28",
  },
  {
    id: "prod-15",
    merchantId: "merchant-2",
    title: "Waffle Cone Special",
    description: "House-made waffle cone with 3 scoops and all the toppings",
    price: 14,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1560008581-09826d1de69e?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any 3 scoops in a cone",
  },
  {
    id: "prod-16",
    merchantId: "merchant-2",
    title: "Rose Water Sorbet",
    description: "Refreshing rose water sorbet with a hint of lemon and edible petals",
    price: 7,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=400&h=400&fit=crop",
    category: "dessert" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any single sorbet",
  },
  {
    id: "prod-17",
    merchantId: "merchant-3",
    title: "Mezze Feast",
    description: "A spread of 8 traditional mezze dishes: hummus, baba ghanouj, tabbouleh, and more",
    price: 30,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any 8 mezze dishes",
  },
  {
    id: "prod-18",
    merchantId: "merchant-3",
    title: "Grilled Kebab Platter",
    description: "Mixed grill platter with lamb, chicken, and kafta kebabs, sides included",
    price: 35,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any grill platter up to $35",
  },
  {
    id: "prod-19",
    merchantId: "merchant-3",
    title: "Seafood Catch",
    description: "Fresh catch of the day, grilled to perfection with lemon and herbs",
    price: 40,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any seafood dish up to $40",
  },
  {
    id: "prod-20",
    merchantId: "merchant-3",
    title: "Date Night Dinner",
    description: "3-course dinner for two with mezze, main course, and dessert + wine",
    price: 75,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any 3-course dinner for two",
  },
  {
    id: "prod-21",
    merchantId: "merchant-3",
    title: "Manoushe Trio",
    description: "Three manoushe: zaatar, cheese, and lahem bi ajin with fresh veggies",
    price: 12,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any 3 manoushe varieties",
  },
  {
    id: "prod-22",
    merchantId: "merchant-3",
    title: "Kibbeh Combo",
    description: "Kibbeh nayyeh with fresh herbs, olive oil, and warm pita bread",
    price: 18,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any kibbeh dish up to $18",
  },
  {
    id: "prod-23",
    merchantId: "merchant-3",
    title: "Lebanese Wine Tasting",
    description: "Flight of 4 Lebanese wines from Bekaa Valley with cheese pairing",
    price: 28,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any wine flight + pairing",
  },
  {
    id: "prod-24",
    merchantId: "merchant-3",
    title: "Family Table",
    description: "A generous family-style spread for 4-6 people with all the classics",
    price: 95,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1547573854-74d2a71d0826?w=400&h=400&fit=crop",
    category: "meals" as CategoryType,
    isActive: true,
    substitutionPolicy: "Any family meal for 4-6",
  },
];
